### ISSUE TITLE
Feature request: Better visibility for strokes, that are too fast.

### ISSUE THREAD

**Issue by Slibowitz** [OpenFunscripter/OFS#30]
Hello!

I would like to present you a feature request.

When scripting, I don't always see, when strokes are too fast. Or I have to pay close attention to it and because of that, I need more time scripting. That's why I would like to have an easy indicator, when a stroke is too fast. 

For example: A blue line would mark the stroke, that is too fast (maybe an option, to choose the color would be cool). 

![Unbenannt](https://user-images.githubusercontent.com/77641504/168486636-587e0439-0a5a-40d8-a299-642cf534f5fb.png)

Also, how about an option, where I could set the desired max speed? When a stroke is higher, than the set max speed, it gets marked.

Thank you very much for reading my request.

Slibowitz

**Comment by OpenFunscripter** [comment]
I can add this shouldn't be too hard.
It will as an option in the next version, but I can't say when that will be.

**Comment by OpenFunscripter** [comment]
I added it.
Again no idea when I'm creating an actual release.
But you can test it if you want by downloading the zip file here https://github.com/OpenFunscripter/OFS/actions/runs/2353016618

Same as the `translation edition` you'll need to delete the `imgui.ini` from your `%appdata%/OFS/OFS_data/` directory.
Otherwise the window layout will be all over the place.
Under Options->Preferences->Scripting you'll find the new setting.

**Comment by Slibowitz** [comment]
Amazing! Thank you so much for this! This makes scripting much easier for me :)
